[build]
command = "pnpm build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"
SKIP_DB_CHECK = "true"

[functions]
included_files = ["node_modules/.geo/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"
